name: Pandoc Markdown to Beamer PDF (Containerized)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    container: pandoc/latex:2.19
    permissions:
      contents: write # This grants write access to the repository contents
      pages: write    # Required for the peaceiris/actions-gh-pages action to publish to GitHub Pages
      id-token: write # Required for some GitHub Pages deployments (e.g., if using OIDC)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install make
      run: |
        apt-get update && apt-get install -y make # Install make inside the container

    - name: Run Makefile target 'md2pdf'
      run: |
        make md2pdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: beamer-pdf
        path: presentation.pdf

  deploy_to_gh_pages:
    needs: build_pdf
    runs-on: ubuntu-latest
    if: success()
    permissions:
      contents: write # This job also needs write access to deploy
      pages: write
      id-token: write # peaceiris/actions-gh-pages uses this internally

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download PDF artifact
      uses: actions/download-artifact@v4
      with:
        name: beamer-pdf
        path: .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
