name: Pandoc Markdown to Beamer PDF (Simplified Run)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    container: pandoc/latex:2.19 # Or your preferred specific Pandoc/LaTeX container
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Missing LaTeX Packages (pgf)
      run: |
        # Use 'apt' to install texlive-pictures, which contains pgfopts.sty
        # Fallback to apt-get if 'apt' isn't found (though 'apt' is more modern)
        if command -v apt; then
          apt update && apt install -y texlive-pictures
        elif command -v apt-get; then
          apt-get update && apt-get install -y texlive-pictures
        else
          echo "Neither apt nor apt-get found. Cannot install missing LaTeX packages."
          exit 1
        fi


    - name: Compile PDF with Pandoc
      run: |
        # IMPORTANT: Replace 'presentation.md' and 'presentation.pdf' with your actual filenames.
        # Ensure 'ukceh.latex' exists in your repository's root, or provide its full path.
        pandoc -s --template ukceh.latex -o slides.pdf slides.md --to=beamer
        # Add any other pandoc options here if needed, e.g.:
        # --citeproc --bibliography=references.bib

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: beamer-pdf
        path: slides.pdf # This must match the -o output file name above

  deploy_to_gh_pages:
    needs: build_pdf
    runs-on: ubuntu-latest
    if: success()
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download PDF artifact
      uses: actions/download-artifact@v4
      with:
        name: beamer-pdf
        path: .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
