name: Pandoc Markdown to Beamer PDF (Robust Build)

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch (or your default branch)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    # Switch to a standard Ubuntu container where apt is guaranteed
    container: ubuntu:latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Pandoc, Full TeX Live, and build essentials
      run: |
        # Update package lists
        #####apt update

        # Install necessary packages:
        # pandoc: The Markdown converter
        # texlive-full: Comprehensive TeX Live distribution (includes Beamer, pgf, etc.)
        #               NOTE: This is a very large install and will take several minutes.
        # build-essential: Often helpful for compiling other tools, includes 'make'
        # git: Needed by actions/checkout sometimes, good to have.
        #### apt install -y pandoc texlive-full build-essential git

        # If texlive-full is too slow, you can try a more selective install:
        # apt install -y pandoc \
        #   texlive-latex-base \
        #   texlive-latex-extra \
        #   texlive-fonts-recommended \
        #   texlive-pictures \
        #   texlive-binaries \
        #   texlive-science \
        #   texlive-xetex \
        #   texlive-luatex \
        #   texlive-lang-european \
        #   make # make is included in build-essential, but keeping for clarity if you switch

    - name: Compile PDF with Pandoc
      run: |
        cd presentation
        ls
        # IMPORTANT: Replace 'presentation.md' and 'presentation.pdf' with your actual filenames.
        # Ensure 'ukceh.latex' exists in your repository's root, or provide its full path.
        pandoc -s --template ukceh.latex -o presentation.pdf slides.md --to=beamer
        # Add any other pandoc options here if needed, e.g.:
        # --citeproc --bibliography=references.bib

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: beamer-pdf
        path: presentation.pdf

  deploy_to_gh_pages:
    needs: build_pdf
    runs-on: ubuntu-latest
    if: success()
    permissions:
      contents: write # Needed to push to gh-pages branch
      pages: write    # Official permission for GitHub Pages
      id-token: write # Often needed for GH Pages internal auth

    steps:
    - name: Download PDF artifact
      uses: actions/download-artifact@v4
      with:
        name: beamer-pdf
        path: ./publish_root # Download the PDF into a temporary directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish_root # Publish ONLY the content of this temporary directory
